FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    libboost-all-dev \
    libpqxx-dev \
    libcpprest-dev \
    nlohmann-json3-dev \
    pkg-config \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY lib/http-service ./lib/http-service
COPY chinta ./chinta

RUN mkdir build && cd build && \
    cmake .. && \
    make -j4

RUN cp build/chinta /usr/local/bin/

EXPOSE 8080

CMD ["/usr/local/bin/chinta", "--config", "/etc/chinta/chinta.yaml"]
