FROM ubuntu:22.04

RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY chinta-web/requirements.txt .

RUN pip3 install -r requirements.txt

COPY chinta-web .

EXPOSE 8000

CMD ["python3", "app.py", "--config", "/etc/chinta/chinta-web.yaml"]
